"""Triage agent prompts."""
from .interaction import SIMPLE_TRIAGE_PROMPT, TRIAGE_SYSTEM_PROMPT
from .interaction_llamacpp import SIMPLE_TRIAGE_PROMPT_NO_THOUGHT
from .extraction import TRIAGE_EXTRACTION_PROMPT
from .extraction_incremental import TRIAGE_EXTRACTION_INCREMENTAL_PROMPT
from .report import TRIAGE_REPORT_PROMPT

__all__ = [
    "SIMPLE_TRIAGE_PROMPT",
    "SIMPLE_TRIAGE_PROMPT_NO_THOUGHT",
    "TRIAGE_SYSTEM_PROMPT",
    "TRIAGE_EXTRACTION_PROMPT",
    "TRIAGE_EXTRACTION_INCREMENTAL_PROMPT",
    "TRIAGE_REPORT_PROMPT",
]
